### ISSUE TITLE
Add CLI tool to exercise type system

### ISSUE THREAD

**Issue by ahpook** [lyraproj/dgo#2]
As an end user of a tool that uses dgo types, I'd like a simple command line tool to interact with the type system so I can explore the types and validate syntax against inputs.

I'd imagine this would take two arguments which point to files on the filesystem: one for the description of the parameters and one for the inputs. Mocking up the `spf13/cobra` style help output:

```
$ dgo --help

dgo: a command line tool to interact with the dgo type system

Usage: 
  dgo [command] [flags]

Available commands:
  help          Shows this help
  validate    Validates input file against a parameter description

Available flags:
  -d, --debug   Be incredibly verbose in output

Use "dgo [command] --help" for more information about a command.

$ dgo validate --help
Validate input against the dgo type system

Usage:
  dgo validate [flags]

Aliases:
  v, val, valid

Flags:
  -i, --input   Relative or absolute path to a yaml file containing input to validate
  -s, --spec  Relative or absolute path to a yaml file with the parameter definitions

Global Flags:
  -d, --debug   Be incredibly verbose in output
```

(Not sure that "spec" is the right name for the last one, I'm open to suggestions!)

Mocked up output:

```
$ dgo val -s ./myspec.yaml -i ./goodinputs.yaml
Got input yaml with:
  host: example.com
  port: 22
Validating 'host' against definition:  string[1]
  'host' OK!
Validating 'port' against definition: 1..999
  'port' OK!
```
And now some bad input:

```
$ dgo vali -s ./myspec.yaml -i ./badinputs.yaml
Got input yaml with:
  host: [example.com, example.io]
  port: 2222
Validating 'host' against definition:  string[1]
  'host' FAILED!
  Reason: expected 'string', got 'array'
Validating 'port' against definition: 1..999
  'port' FAILED!
  Reason: expected integer in inclusive range from 1 to 999, got 2222
```

**Comment by thallgren** [comment]
Added almost according to spec. There are two differences.

1. The command uses --verbose or -v to describe verbose output rather than --debug. Reason being that the term "debug" is related to logging and there's no debug logging available in dgo (I want dgo to avoid being opinionated about logging).
2. The output of the examples, verbose as they are,  is enabled by the verbose flag. Running without verbose will yield complete silence for successful validation and more dense output on failures. Sample output with --verbose:
    ```
    Got input yaml with:
      port: 22
    Validating 'host' against definition string[1]
      'host' FAILED!
      Reason: required key not found in input
    Validating 'port' against definition 1..999
      'port' OK!
    ```
    Output from the same validation without --verbose
    ```
    missing required parameter 'host'
    ```
